
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REGISTER_USER_BEGIN = 'RESGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'RESGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'RESGISTER_USER_ERROR'

