
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'RESGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'RESGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'RESGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'
